<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            
            // Jacket Products =========================================================================
            [
                'name' => 'Winter Jacket',
                'slug' => 'winter-jacket',
                'description' => 'Warm and cozy winter jacket',
                'price' => 499000,
                'category' => 'jacket',
                'image' => 'j1.png',
                'stock' => 10,
                'is_active' => 1,
            ],
            [
                'name' => 'black Light Jacket',
                'slug' => 'black-light-jacket',
                'description' => 'Lightweight jacket for everyday use',
                'price' => 399000,
                'category' => 'jacket',
                'image' => 'J2.png',
                'stock' => 15,
                'is_active' => 1,
            ],
            [
                'name' => 'sweater snow white',
                'slug' => 'sweater-snow-white',
                'description' => 'Elegant sweater for special occasions',
                'price' => 1200000,
                'category' => 'jacket',
                'image' => 'J3.png',
                'stock' => 11,
                'is_active' => 1,
            ],
            [
                'name' => 'colorful sweater ',
                'slug' => 'colorful-sweater',
                'description' => 'colorful sweater for a vibrant look',
                'price' => 799000,
                'category' => 'jacket',
                'image' => 'J4.png',
                'stock' => 13,
                'is_active' => 1,
            ],
            [
                'name' => 'color sweater ',
                'slug' => 'color-sweater',
                'description' => 'color sweater for stylish appearance',
                'price' => 599000,
                'category' => 'jacket',
                'image' => 'J5.png',
                'stock' => 20,
                'is_active' => 1,
            ],
            [
                'name' => 'dinamis color sweater ',
                'slug' => 'dinamis-color-sweater',
                'description' => 'dinamis color sweater for stylish shine',
                'price' => 899000,
                'category' => 'jacket',
                'image' => 'J6.png',
                'stock' => 8,
                'is_active' => 1,
            ],
            [
                'name' => 'leaf sweater ',
                'slug' => 'leaf-sweater',
                'description' => 'leaf sweater for trendy look',
                'price' => 699000,
                'category' => 'jacket',
                'image' => 'J7.png',
                'stock' => 12,
                'is_active' => 1,
            ],
            [
                'name' => 'leafer sweater ',
                'slug' => 'leafer-sweater',
                'description' => 'leafer sweater for casual style',
                'price' => 799000,
                'category' => 'jacket',
                'image' => 'J8.png',
                'stock' => 14,
                'is_active' => 1,
            ],
            [
                'name' => 'classic sweater ',
                'slug' => 'classic-sweater',
                'description' => 'classic sweater for cool weather',
                'price' => 899000,
                'category' => 'jacket',
                'image' => 'J9.png',
                'stock' => 9,
                'is_active' => 1,
            ],
            [
                'name' => 'dark encode sweater ',
                'slug' => 'dark-encode-sweater',
                'description' => 'dark encode sweater for urban style',
                'price' => 999000,
                'category' => 'jacket',
                'image' => 'J10.png',
                'stock' => 7,
                'is_active' => 1,
            ],
            [
                'name' => 'rider dark jacket ',
                'slug' => 'rider-dark-jacket',
                'description' => 'rider dark jacket for casual vibe',
                'price' => 899000,
                'category' => 'jacket',
                'image' => 'J11.png',
                'stock' => 6,
                'is_active' => 1,
            ],
            [
                'name' => 'warm sweater encode ',
                'slug' => 'warm-sweater-encode',
                'description' => 'warm sweater encode for stylish comfort',
                'price' => 799000,
                'category' => 'jacket',
                'image' => 'J12.png',
                'stock' => 10,
                'is_active' => 1,
            ],
            [
                'name' => 'tunder black jacket  ',
                'slug' => 'tunder-black-jacket',
                'description' => 'tunder black jacket for everyday wear',
                'price' => 699000,
                'category' => 'jacket',
                'image' => 'J13.png',
                'stock' => 15,
                'is_active' => 1,
            ],
            [
                'name' => 'gradient light sweater ',
                'slug' => 'gradient-light-sweater',
                'description' => 'gradient light sweater for casual outings',
                'price' => 599000,
                'category' => 'jacket',
                'image' => 'J14.png',
                'stock' => 18,
                'is_active' => 1,
            ],
            
            // Shirt Products ===========================================================================
            [
                'name' => 'Formal Shirt',
                'slug' => 'formal-shirt',
                'description' => 'Elegant formal shirt for play or work',
                'price' => 299000,
                'category' => 'shirt',
                'image' => 's1.png',
                'stock' => 25,
                'is_active' => 1,
            ],
            [
                'name' => 'blue casual Shirt',
                'slug' => 'blue-casual-shirt',
                'description' => 'Comfortable casual shirt',
                'price' => 249000,
                'category' => 'shirt',
                'image' => 's2.png',
                'stock' => 35,
                'is_active' => 1,
            ],
            [
                'name' => 'dark Shirt',
                'slug' => 'dark-shirt',
                'description' => 'Stylish dark shirt for everyday wear',
                'price' => 199000,
                'category' => 'shirt',
                'image' => 's3.png',
                'stock' => 20,
                'is_active' => 1,
            ],
            [
                'name' => 'grey brave Shirt',
                'slug' => 'grey-brave-shirt',
                'description' => 'Classic grey brave shirt for all occasions',
                'price' => 219000,
                'category' => 'shirt',
                'image' => 's4.png',
                'stock' => 30,
                'is_active' => 1,
            ],
            [
                'name' => 'white casual Shirt',
                'slug' => 'white-casual-shirt',
                'description' => 'Light and airy white casual shirt',
                'price' => 229000,
                'category' => 'shirt',
                'image' => 's5.png',
                'stock' => 28,
                'is_active' => 1,
            ],
            [
                'name' => 'modern Shirt',
                'slug' => 'modern-shirt',
                'description' => 'Vibrant modern shirt for a bold look',
                'price' => 259000,
                'category' => 'shirt',
                'image' => 's6.png',
                'stock' => 22,
                'is_active' => 1,
            ],
            [
                'name' => 'wave rainbow Shirt',
                'slug' => 'wave-rainbow-shirt',
                'description' => 'Trendy wave rainbow casual shirt',
                'price' => 239000,
                'category' => 'shirt',
                'image' => 's7.png',
                'stock' => 26,
                'is_active' => 1,
            ],
            [
                'name' => 'grafik Shirt',
                'slug' => 'grafik-shirt',
                'description' => 'Striped formal shirt for a professional look',
                'price' => 279000,
                'category' => 'shirt',
                'image' => 's8.png',
                'stock' => 18,
                'is_active' => 1,
            ], 
            [
                'name' => 'flexing Shirt',
                'slug' => 'flexing-shirt',
                'description' => 'Flexing shirt for everyday elegance',
                'price' => 189000,
                'category' => 'shirt',
                'image' => 's9.png',
                'stock' => 32,
                'is_active' => 1,
            ],
            [
                'name' => 'stylis Shirt',
                'slug' => 'stylis-shirt',
                'description' => 'Stylis shirt for casual outings',
                'price' => 209000,
                'category' => 'shirt',
                'image' => 's10.png',
                'stock' => 24,
                'is_active' => 1,
            ],
            [
                'name' => 'modernist Shirt',
                'slug' => 'modernist-shirt',
                'description' => 'Modernist shirt for a chic appearance',
                'price' => 269000,
                'category' => 'shirt',
                'image' => 's11.png',
                'stock' => 20,
                'is_active' => 1,
            ],
            [
                'name' => 'casual vibe Shirt',
                'slug' => 'casual-vibe-shirt',
                'description' => 'Casual vibe shirt for relaxed days',
                'price' => 179000,
                'category' => 'shirt',
                'image' => 's12.png',
                'stock' => 29,
                'is_active' => 1,
            ],
            
            // T-Shirt Products =========================================================================
            [
                'name' => 'art T-Shirt',
                'slug' => 'art-t-shirt',
                'description' => 'Cool binary art t-shirt design',
                'price' => 139000,
                'category' => 't-shirt',
                'image' => 'ts1.png',
                'stock' => 20,
                'is_active' => 1,
            ],
            [
                'name' => 'blue sky T-Shirt',
                'slug' => 'blue-sky-t-shirt',
                'description' => 'Blue sky t-shirt with cloud design',
                'price' => 129000,
                'category' => 't-shirt',
                'image' => 'ts2.png',
                'stock' => 30,
                'is_active' => 1,
            ],
            [
                'name' => 'orange T-Shirt',
                'slug' => 'orange-t-shirt',
                'description' => 'Simple orange t-shirt for everyday wear',
                'price' => 89000,
                'category' => 't-shirt',
                'image' => 'ts3.png',
                'stock' => 25,
                'is_active' => 1,
            ],
            [
                'name' => 'square design T-Shirt',
                'slug' => 'square-design-t-shirt',
                'description' => 'Square design t-shirt for a unique look',
                'price' => 119000,
                'category' => 't-shirt',
                'image' => 'ts4.png',
                'stock' => 22,
                'is_active' => 1,
            ],
            [
                'name' => 'bone splash T-Shirt',
                'slug' => 'bone-splash-t-shirt',
                'description' => 'Bone splash t-shirt design',
                'price' => 149000,
                'category' => 't-shirt',
                'image' => 'ts5.png',
                'stock' => 18,
                'is_active' => 1,
            ],
            [
                'name' => 'perfect color T-Shirt',
                'slug' => 'perfect-color-t-shirt',
                'description' => 'Perfect color t-shirt for a sleek look',
                'price' => 109000,
                'category' => 't-shirt',
                'image' => 'ts6.png',
                'stock' => 28,
                'is_active' => 1,
            ],
            [
                'name' => 'clay modern art T-Shirt',
                'slug' => 'clay-modern-art-t-shirt',
                'description' => 'Clay modern art t-shirt design',
                'price' => 139000,
                'category' => 't-shirt',
                'image' => 'ts7.png',
                'stock' => 24,
                'is_active' => 1,
            ],
            [
                'name' => 'block color splash T-Shirt',
                'slug' => 'block-color-splash-t-shirt',
                'description' => 'Block color splash t-shirt for a vibrant look',
                'price' => 129000,
                'category' => 't-shirt',
                'image' => 'ts8.png',
                'stock' => 26,
                'is_active' => 1,
            ],
            [
                'name' => 'tracked modern art T-Shirt',
                'slug' => 'tracked-modern-art-t-shirt',
                'description' => 'Tracked modern art t-shirt design for art lovers',
                'price' => 159000,
                'category' => 't-shirt',
                'image' => 'ts9.png',
                'stock' => 20,
                'is_active' => 1,
            ],
            [
                'name' => 'traditional color splash T-Shirt',
                'slug' => 'traditional-color-splash-t-shirt',
                'description' => 'Traditional color splash t-shirt for a lively appearance',
                'price' => 119000,
                'category' => 't-shirt',
                'image' => 'ts10.png',
                'stock' => 30,
                'is_active' => 1,
            ],
            [
                'name' => 'adat jawa modern art T-Shirt',
                'slug' => 'adat-jawa-modern-art-t-shirt',
                'description' => 'Adat jawa modern art t-shirt design',
                'price' => 139000,
                'category' => 't-shirt',
                'image' => 'ts11.png',
                'stock' => 22,
                'is_active' => 1,
            ],


        ];

    foreach ($products as $product) {
        // Cek dulu apakah slug sudah ada (double safety)
        if (!Product::where('slug', $product['slug'])->exists()) {
            Product::create($product);
        }
    }
    
    $this->command->info('✅ Product seeder completed: ' . count($products) . ' products added.');

    }
}